import argparse

parser=argparse.ArgumentParser(description="Run SPGAT.")
parser.add_argument("--dim", type=int, default=64,help="embedding len")
parser.add_argument("--epoches",type=int,default=100)
parser.add_argument("--lr",type=float,default=1e-4)
parser.add_argument("--weight_decay",type=float,default=5e-4)
parser.add_argument("--batch_size",type=int,default=32)
parser.add_argument("--p",type=float,default=0.2)
parser.add_argument("--cf_batch_size",type=int,default=1024)
parser.add_argument("--kg_batch_size",type=int,default=2048)
parser.add_argument("--test_batch_size",type=int,default=32)
parser.add_argument("--laplacian_type",type=str,default="random-walk")
parser.add_argument('--data_name',type=str, default='last-fm')
parser.add_argument('--data_dir', type=str,default='datasets/')
parser.add_argument('--use_pretrain', type=int, default=0)
parser.add_argument('--pretrain_embedding_dir', type=str, default='datasets/pretrain/')
parser.add_argument('--embed_dim', type=int, default=64)
parser.add_argument("--A",type=float,default=0.2)
parser.add_argument("--n_layers",type=int,default=2)
parser.add_argument("--margin",type=float,default=1.0)
parser.add_argument("--L1_flag",type=bool,default=True)
arg=parser.parse_args()

